# Generated by Django 4.1 on 2022-08-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrainName', models.CharField(max_length=1000)),
                ('Destination', models.CharField(max_length=100)),
            ],
        ),
    ]
