# Generated by Django 4.1 on 2022-08-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railwaystat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=3)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
